### PR TITLE
Wrap file-check with try-except (attempt 2)

### PR DESCRIPTION
**Pull request by michaelbjames**
Bugfix for #50.

I needed to recreate this so that I could be working from a branch based on your `develop` branch.

Again, lmk of any other changes you'd like me to make here.

### CODE REVIEW

**Comment by SamSchott** [comment]
> To continue our discussion about link-behavior:
> Perhaps it would be sensible for the default to follow dropbox's convention, but permit a flag or configuration value to allow following of symlinks? This PR of course isn't the place for that, but I'm just offering my two cents.

Yes, that's a good idea. I typically prefer providing only one (the "best") option, but there really is a use case for syncing folder's outside of the Dropbox directory. 

> I saw another place in monitor.py where the same logic that caused #50, for when a file gets modified.

Good catch.

**Comment by SamSchott** [comment]
> I don't quite like that duplicated logic

You can move the code to a private method `UpDownSync._wait_for_creation` (or any better name) if you like.

> Again, lmk of any other changes you'd like me to make here.

One last request: Could you just exit the while loop with `break` instead of raising an exception here? For now, I prefer raising all exceptions from MaestralApiClient. A broken symlink will be handled there automatically.

**Comment by michaelbjames** [comment]
Good suggestion. I moved those two while-true loops to a static method.
In the static method, `return` and `break` serve the same semantic job, but IMO return is clearer here.
Further, in its current usage now, the try-catch is equivalent to using a `break` in the original, in-line, PR.

I didn't realize I didn't need to raise the exception there. You're right, I let it go and I still get the broken symlink in the sync errors list.

Thanks for your help on the PR!

**Comment by SamSchott** [comment]
Perfect, thank you!

**Pull request merged**
