### PR TITLE
Add snap support

### PR DESCRIPTION
**Pull request by LyzardKing**
This PR adds a working confined snap.
For now it needs to be connected to the kde content snap, but a request for autoconnection can be opened on the snapcraft forum.

### CODE REVIEW

**Comment by LyzardKing** [comment]
The appindicator icon issue is not fixed yet! it might need also another override..
I'll test and upload the new fix

**Comment by LyzardKing** [comment]
It works if XDG_CURRENT_DESKTOP is set to Unity7

**Comment by SamSchott** [comment]
I just gave this a try and it seems to have similar issues as my snap:

1. It deals badly with hi-dpi scaling (many widgets appear at half the actual size).
2. The system tray icon still does not show.
3. There is an issue with the terminal encoding and the CLI. But that is easily fixed by setting the environment variables `LC_ALL=C.UTF-8` and `LANG=C.UTF-8`.
4. Qt throws lots of errors about not being able to send dbus messages. But this should probably be expected...

Here is the screenshot of the setup window from the snap:

Screenshot 2020-03-28 at 21 30 38

And here is how it should look, installed with pip:

Screenshot 2020-03-28 at 21 34 36

I really don't understand the choices behind snap sandboxing. MacOS has had sandboxing for quite some time now but this does not prevent the apps form getting read access to standard system resources or write access to *its own* config and resource folders (e.g., in `~/.config/appname`)

**Comment by LyzardKing** [comment]
There should be a fix for the theming (and hi-dpi)..
The indicator is shown on my computer.. I'll try in a clean vm..

**Comment by LyzardKing** [comment]
Does it work if you run `QT_AUTO_SCREEN_SCALE_FACTOR=0 maestral.maestral-qt`
If it does it can be added to the environment in the snapcraft.yaml
I think the proper value is 0, but it might be 1... I cannot remember

**Comment by LyzardKing** [comment]
Snaps have access to their own config/resource folder, but it's relocated to ~/.snap/maestral/current/.config/maestral, so it's isolated from the rest of the system.
Every snap has it's own fake home folder for config/tmp files/...
I'm not a snap architect, so I cannot speak for the merits of the system, just that this is how it works.

**Comment by LyzardKing** [comment]
The indicator should work now if you were previously running `maestral gui`

**Comment by SamSchott** [comment]
> Snaps have access to their own config/resource folder

Yes, that is their design choice. A bit confusing to users but fair enough.

> Does it work if you run QT_AUTO_SCREEN_SCALE_FACTOR=0 maestral.maestral-qt

It does not work unfortunately. Qt should automatically detect high-dpi scaling and adjust accordingly if the `AA_EnableHighDpiScaling` flag it set (which it is). As far as I understand, this flag can be set by the user with `QT_AUTO_SCREEN_SCALE_FACTOR=1` if the application already does not do so itself.

**Comment by SamSchott** [comment]
I have also tried the new snap. The tray icon still not show, for either the desktop entry or the `maestral gui` command. Not sure why. I know that Qt tries to use D-Bus StatusNotifier when possible but I am not sure what the fallback option is.

I am running it on a clean Ubuntu 19.10 VM.

**Comment by SamSchott** [comment]
Another issue I have noticed: there is a memory leak trying to show the tray icon. I noticed when debugging the issue inside the snap's shell (`snap run --shell maestral`). Memory usage increases by the tray icon size every second when Qt tries and fails to set the icon.

**Comment by LyzardKing** [comment]
Strange..
Does the memory leak happen also with the TMPDIR option added back to envorinment in the snap yaml?

**Comment by SamSchott** [comment]
I'll give it a try.

**Comment by SamSchott** [comment]
I'm afraid it is still leaking memory and the icon does not show either.

**Comment by LyzardKing** [comment]
Did you connect the snap to the kde content snap?
`snap connect maestral:kde-frameworks-5-plug kde-frameworks-5-core18:kde-frameworks-5-core18-slot`

**Comment by SamSchott** [comment]
Of course.

**Comment by SamSchott** [comment]
Some progress on the high-dpi scaling: it works when manually setting the environment variable `QT_SCREEN_SCALE_FACTORS` to a list of appropriate scale factors for each screen. The problem seems to be that Qt cannot get the scaling which the user sets in "Settings > Devices Screen Display". Possibly another one of those sandboxing decisions? This does not seem to be issue with snaps that use Gtk.

Regarding the appindicator / sys tray icon, I am lost. I know that Qt tries to set it via Dbus, but the Unity7 plug should give it permissions to do so, right?

**Comment by LyzardKing** [comment]
I had that same issue with other qt applications (not snaps) so I assume it's a qt issue.
Unity7 gives the permission to use the appindicator. If you remove that plug it should show the older systray icon. I tried removing completely and rebuilding and I can successfully see the appindicator.

**Comment by SamSchott** [comment]
> I had that same issue with other qt applications (not snaps) so I assume it's a qt issue.

It should not be an issue with qt as long as the app enables `AA_EnableHighDpiScaling`, which some qt apps forget to do if the developers don't routinely use Linux on high-dpi screens. macOS completely abstracts high-dpi scaling so there is no need to bother.

> I tried removing completely and rebuilding and I can successfully see the appindicator.

That does not seem to work for me either :/ This must be either some difference in packaging the snap (which I am doing on macOS) or with the Ubuntu VM which I am using.

**Comment by LyzardKing** [comment]
Ok, so I tested the snap I built on an ubuntu (gnome) vm and it fails to show the indicator.
In an ubuntu-mate vm it works perfectly.
I'll try and ask on the snapcraft forum, but it seems to be an issue with the connection between snapd and the indicator extension in gnome.

**Comment by SamSchott** [comment]
Lets see if we get a helpful response from the community. As far as I can see from the Unity7 interface specification [here](https://github.com/snapcore/snapd/blob/master/interfaces/builtin/unity7.go), all necessary permissions are given. Sending desktop notifications via Dbus for instance works perfectly well.

**Comment by LyzardKing** [comment]
with this option set under `environment` it works in the clean ubuntu gnome vm:
`QT_QPA_PLATFORMTHEME: gtk3`
I'm trying now to rebuild without the other ones..

**Comment by SamSchott** [comment]
Unfortunately it still does not work for me 😟 Monitoring the dbus activity, I can see that Qt send both the icon path `/run/user/1000/snap.maestral/qt-trayicon-BDHjwk.png` (is this the correct runtime dir for the snap?) as well as the raw pixmap data. Setting `QT_QPA_PLATFORMTHEME=gtk3` does not make a difference in that communication.

<details><summary>dbus-monitor output</summary>
<p>

```shell
method return time=1585582358.458033 sender=:1.309 -> destination=:1.38 serial=33 reply_serial=18877
   array [
      dict entry(
         string "AttentionIconName"
         variant             string ""
      )
      dict entry(
         string "AttentionIconPixmap"
         variant             array [
               struct {
                  int32 0
                  int32 0
                  array [
                  ]
               }
               struct {
                  int32 0
                  int32 0
                  array [
                  ]
               }
            ]
      )
      dict entry(
         string "AttentionMovieName"
         variant             string ""
      )
      dict entry(
         string "Category"
         variant             string "ApplicationStatus"
      )
      dict entry(
         string "IconName"
         variant             string "/run/user/1000/snap.maestral/qt-trayicon-BDHjwk.png"
      )
      dict entry(
         string "IconPixmap"
         variant             array [
               struct {
                  int32 22
                  int32 22
                  array of bytes [
                    ...
                  ]
               }
               struct {
                  int32 64
                  int32 64
                  array of bytes [
                    ...
                  ]
               }
            ]
      )
      dict entry(
         string "Id"
         variant             string "Maestral"
      )
      dict entry(
         string "ItemIsMenu"
         variant             boolean false
      )
      dict entry(
         string "Menu"
         variant             object path "/MenuBar"
      )
      dict entry(
         string "OverlayIconName"
         variant             string ""
      )
      dict entry(
         string "OverlayIconPixmap"
         variant             array [
            ]
      )
      dict entry(
         string "Status"
         variant             string "Active"
      )
      dict entry(
         string "Title"
         variant             string "Maestral"
      )
      dict entry(
         string "ToolTip"
         variant             struct {
               string ""
               array [
               ]
               string "Not linked."
               string ""
            }
      )
   ]
```
</p>
</details>

**Comment by LyzardKing** [comment]
Strange.. I tried installing in a clean ubuntu vm ..
The only other thing installed is the kde framework snap, so it can be connected.
Did you pass the setting or try installing the snap (I added the env variable in the yaml).
It might be needed to have the variable declared in the snap instead of added at runtime

**Comment by SamSchott** [comment]
Never mind, it does work! Environment variable magic :) However, the icon is black instead of white so I didn't see it on the non-opaque menu bar in Ubuntu 19.10 ...

Now for the wrong icon colour, Maestral determines the correct icon as follows:

1. If it runs on Gnome 3, it attempts to locate the "symbolic" icons which are installed in the hicolor theme. Those are correctly installed in the snap at `/snap/maestral/x2/share/icons`. Those icons will adopt their colour automatically but are only supported in Gnome 3 (KDE uses another spec for symbolic icons which Maestral does not support at the moment). However, Maestral reads the Gnome version from `/usr/share/gnome/gnome-version.xml`, which fails from within the snap. Therefore, it uses its fallback mechanism.

2. As a fallback, it tries to infer the location of status bar and determine its colour by reading pixels  from the screen. It then selects a contrasting icon colour. This also fails from within the snap.

3. Maestral gives up and reverts to black PNG icons.

To support snaps on multiple platforms, one would ideally get both step 1 and step 2 right. Detecting Gnome 3 should be possible from within the snap and will likely involve some change to maestral itself. Step 2 might need another plug?

**Comment by LyzardKing** [comment]
1. should be possible by adding another plug for system file read access (https://snapcraft.io/docs/system-files-interface), but it wouldn't be auto-connected, so it be better to inquire whether it would be connected after a request.
2. would might not work in the snap at all..

As a sidenote.. is anything using gnome2 atm? xfce and mate are both (mosty) gtk3..
Should the check be on XDG_SESSION_DESKTOP (so you could determine whether KDE is in use?

**Comment by SamSchott** [comment]
1. Yes, I am using Gnome2! We have a number of PCs in our lab that still run CentOS 6 to support legacy software.

   XDG_SESSION_DESKTOP is checked, that is exactly how I determine if KDE is used. I just haven't gotten around to creating SVG icons that follow their symbolic spec.

2. There are some snaps for screenshots such as https://github.com/flameshotapp. I'll have a look at their plugs. Its unlikely an autoconnect is granted just to determine the status bar colour.

**Comment by LyzardKing** [comment]
Ah ok!
Couldn't XDG_SESSION_DESKTOP be used to identify a gnome2 DE?

**Comment by SamSchott** [comment]
I stand corrected, I am not using XDG_SESSION_DESKTOP but only XDG_CURRENT_DESKTOP and GDMSESSION at the moment.

**Comment by LyzardKing** [comment]
Ah.. in the snap we set XDG_CURRENT_DESKTOP to Unity.
It might be possible to set it in the snapcraft.yaml to
`XDG_CURRENT_DESKTOP: Unity:$XDG_CURRENT_DESKTOP`
to see it it retains the part you're using..

**Comment by SamSchott** [comment]
Yeah, I noticed that. But is setting `XDG_CURRENT_DESKTOP` really necessary? It works absolutely fine with `QT_QPA_PLATFORMTHEME: gtk3` for me.

**Comment by LyzardKing** [comment]
Did you test it already without that variable set?
I'll try and rebuild/run with just QT_QPA_PLATFORMTHEME and test on ubuntu and ubuntu-mate.
If it's not needed better!

**Comment by LyzardKing** [comment]
I tried, and I cannot see the icon if XDG_CURRENT_DESKTOP is not set to unity...
I can set it like this to show also the "real" desktop:
`XDG_CURRENT_DESKTOP: "Unity:$XDG_CURRENT_DESKTOP"`

**Comment by SamSchott** [comment]
Ok, `XDG_CURRENT_DESKTOP: "Unity:$XDG_CURRENT_DESKTOP"` should work as well.

A few issues which I noticed when trying out the snap:

1. The snap defaults to selecting `x3` or a similar directory instead `~/snap` for the Dropbox folder. This is an unexpected user experience. However, changing `HOME` may have some adverse effects on where config files are stored unless `XDG_CONFIG_HOME` it set. Luckily, it looks like the desktop launcher sets `XDG_CONFIG_HOME` correctly, despite it being not set in Ubuntu by default.

2. File / folder chooser dialogs appear to be run by another process. This makes sense for sandboxing but the implementation here causes several issues:

   * The chooser appears underneath the respective window which launched it (settings pane, setup dialog). This appears to be issue with the Maestral windows set to always stay on top combined with the chooser running in a different process. Keeping the settings window etc on top is only really necessary for macOS where a system tray app does not get a dock entry and windows can get "lost". This can be changed for Linux.
   * Configurations such as choosing / displaying only folders are not respected.

3. A cosmetic detail: system themes are not applied for icons etc.

4. I still struggle to automatically enable high-dpi scaling and have noticed that other Qt snaps don't get this right either (eg. https://redisdesktop.com) even through the natively packaged versions work well.

**Comment by LyzardKing** [comment]
System themes should work, but for themes contained in the snap `gtk-common-themes`
I've had issues myself with the folder chooser.. that might be an issue/bug to report on the forum.
The snap has full access to it's "fake" home folder, so that it can be used for the configurations without escaping the confinement. In maestral (or via an env variable) it could be possible to set the folder dialog to default to the "real" home
Unfortunately I cannot properly test the high-dpi part, but I did see some fixes a while back in the snapcraft forum.

**Comment by SamSchott** [comment]
> System themes should work, but for themes contained in the snap gtk-common-themes

Strange. Maybe Ubuntu's Yaru theme is not yet included in `gtk-common-themes`.

> The snap has full access to it's "fake" home folder, so that it can be used for the configurations without escaping the confinement. In maestral (or via an env variable) it could be possible to set the folder dialog to default to the "real" home

This is not really a folder dialog issue but rather a problem with Maestral defaulting to the "wrong" folder without the user selecting one. But is should be fixable with environment variables. 

I can look into the high-dpi issue. It probably is related to Qt looking at the wrong settings.

**Comment by LyzardKing** [comment]
Yaru is for sure in the gtk-common-themes..
Could be that this package is missing in the stage-snaps part:
`qt5-gtk-platformtheme`

I'll try and rebuild and let you know

**Comment by LyzardKing** [comment]
No.. I tried a few different packages that were suggested in the forum and it doesn't work.
It's strange, because the snap is connected to the gtk-common-themes content snap, and that is used for themes, cursors, icons.

**Comment by SamSchott** [comment]
Progress on some fronts:

1. Setting HOME to /home/$USER works on most systems (with standard home directory locations) to give sane defaults. The alternative would be to set HOME in a wrapper launch script which uses more robust checks than $USER. A discussion of possible options is given [here](https://forum.snapcraft.io/t/accessing-home-directory-with-home-interface/6672/5). This has also revealed a bug in Maestral: the data dir was accidentally set to XDG_DATA_DIR instead of XDG_DATA_HOME. The former won't be set in our snap environment.

2. The open file dialogs: Qt uses [xdg-desktop-portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html) when it detects that it is running in a snap. Initially developed for flatpak, this dbus interface supports choosing files vs directories. However, it seems like this is only properly support in Qt 5.12 and higher while the snap currently uses version 5.9.5. Would it be possible to use a newer version of Qt? I also suspect that this would improve high-dpi support...

3. While we are updating versions: Is there any benefit in using Python 3.6? Python 3.8 may provide significant performance improvements for copying and removing file trees, depending on the platform and file system. Both are frequent use cases in downloads and conflict handling.

**Comment by SamSchott** [comment]
Just a note to myself, for future reference: The autostart functionality will need testing.

1. GUI: Maestral has checkbox to start the GUI on login and does so by creating a .desktop entry at `~/.config/autostart` with the appropriate launch command. This approach seems to be currently not supported by snaps, even through there is some discussion on the [forum](https://forum.snapcraft.io/t/how-to-autostart-a-snap-of-a-desktop-application/2449/41).

2. Daemon: Maestral creates autostart entries by calling `systemctl --user enable` on a .service file which is generated at runtime to launch the correct config and executable. I am not sure if this is or will be possible from a snap.

The relevant module is `maestral.utils.autostart` and template files are in maestral/resources.

**Comment by LyzardKing** [comment]
I'm testing the snap with an autostart option, as described here: https://snapcraft.io/docs/snap-format.
I added `autostart: maestral-maestral.desktop` under `apps: maestral-qt:`
but it doesn't seem to work.

Regarding the daemon: that is feasible with https://snapcraft.io/docs/service-management
by tagging in the yaml the daemon.
I've never tried this approach but it should work

**Comment by LyzardKing** [comment]
The autostart .desktop file has the incorrect Exec line:
it point so `/snap/maestral/x14/bin/maestral gui -c 'maestral'`
instead of either `maestral gui -c 'maestral'`
or `/snap/bin/maestral gui -c 'maestral'`

**Comment by LyzardKing** [comment]
I removed the extra maestral-qt command.
Now the snap functions like the normal version (calling maestral gui will start the ui)
I tried changing the autostart .desktop file to the spec, but it doesn't start on boot.

**Comment by SamSchott** [comment]
> The autostart .desktop file has the incorrect Exec line

It seems like `which maestral` returns `/snap/maestral/x4/bin/maestral` from inside the snap, which of course only works from within the snap. The reason to use an absolute path in the first place is to prevent issues when maestral is installed for the user only and its executable may not be in PATH. But I am not sure if this is really necessary.

Regarding the daemon, that does seem feasible. I will have to look into the details of having different services for different config names. This is currently done through systemd's service "templates" with the `maestral-daemon@.service` syntax so that any number of services can coexist to sync multiple accounts.

In any case, a snap seems to control its own services with `snapctl`. It may therefore be necessary to include explicit snap awareness in the autostart module.

**Comment by SamSchott** [comment]
Regarding newer versions of Qt and Python, the easiest way may be to just switch to the core20 base.

**Comment by LyzardKing** [comment]
At the moment core20 is not fully developed.. especially the kde content interface.
But if you want to update the qt version we could link to `kde-frameworks-5-qt-5-14-core18` instead of `kde-frameworks-5-qt-core18`
I'll try it now

**Comment by SamSchott** [comment]
Yes, I agree. For now, the snap is in good shape and I expect that the remaining issues with folder selection dialogs will be fixed with a qt upgrade in core20. The high-dpi scaling issue certainly lies with Qt 5.9 and not with the snap environment, I can reproduce it outside of the snap.

Same goes for kde-neon: if I understand the forum posts correctly, the reviewers are reluctant to grant individual autoconnect requests for kde-frameworks-5-qt-core18 and would prefer a global autoconnect. 

I think the easiest way right now really is to wait for core20 and kde-frameworks-5-qt-core20, both may even come some time this month.

I am going to merge this and aim for snap support in the autostart module by the time core20 comes out. Thank you for all the work you have put into this!

**Comment by SamSchott** [comment]
PS: I have learned a lot about snaps and their unique approach to sandboxing!

**Comment by SamSchott** [comment]
I guess the Qt 5.9 requirement really is a *minimum* requirement. It won't crash, but it won't look good on several platforms systems either.

**Pull request merged**
